# Generated by Django 3.2 on 2022-08-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_skates_size',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
