# Generated by Django 3.2 on 2022-08-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clothes_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='skate_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
